#!/usr/bin/env python3
"""
Generatore automatico di file di supporto per save_pandetta.py
Analizza le importazioni e genera/aggiorna requirements.txt.
"""

import ast
import os
import sys
import subprocess
from pathlib import Path
from typing import Set

def get_standard_lib_modules() -> Set[str]:
    """ Ottiene la lista dei moduli della standard library Python. """
    try:
        import sys
        if hasattr(sys, 'stdlib_module_names'):
            return set(sys.stdlib_module_names)
    except Exception:
        pass
    
    # Fallback: lista comune per Python 3.8+ (può essere espansa)
    common_stdlibs = {
        'abc', 'argparse', 'array', 'ast', 'asyncio', 'atexit', 'base64',
        'bisect', 'calendar', 'cgi', 'cgitb', 'chunk', 'cmath', 'collections',
        'concurrent', 'contextlib', 'copy', 'csv', 'dataclasses', 'datetime',
        'decimal', 'difflib', 'dis', 'email', 'encodings', 'ensurepip',
        'enum', 'filecmp', 'fileinput', 'fnmatch', 'fractions', 'functools',
        'gc', 'getopt', 'glob', 'gzip', 'hashlib', 'heapq', 'http', 'imaplib',
        'imghdr', 'inspect', 'io', 'ipaddress', 'json', 'keyword', 'lib2to3',
        'logging', 'mailbox', 'marshal', 'math', 'mimetypes', 'mmap',
        'modulefinder', 'multiprocessing', 'netrc', 'nis', 'nntplib',
        'numbers', 'operator', 'os', 'pathlib', 'pdb', 'pickle', 'pickletools',
        'pipes', 'pkgutil', 'platform', 'poplib', 'posix', 'pprint', 'profile',
        'pstats', 'queue', 'quopri', 'random', 're', 'reprlib', 'resource',
        'rlcompleter', 'runpy', 'sched', 'secrets', 'select', 'selectors',
        'shelve', 'shlex', 'shutil', 'signal', 'site', 'smtpd', 'smtplib',
        'sndhdr', 'socket', 'socketserver', 'spwd', 'sqlite3', 'ssl',
        'stat', 'statistics', 'string', 'stringprep', 'struct', 'subprocess',
        'sunau', 'symbol', 'symtable', 'sys', 'sysconfig', 'tabnanny',
        'tarfile', 'telnetlib', 'tempfile', 'textwrap', 'threading', 'time',
        'timeit', 'tkinter', 'token', 'tokenize', 'trace', 'traceback',
        'tracemalloc', 'tty', 'turtle', 'turtledemo', 'types', 'typing',
        'unittest', 'urllib', 'uuid', 'venv', 'warnings', 'wave', 'weakref',
        'webbrowser', 'wsgiref', 'xdrlib', 'xml', 'xmlrpc', 'zipapp',
        'zipfile', 'zipimport', 'zlib'
    }
    return common_stdlibs

def get_local_modules(python_dir: Path) -> Set[str]:
    """Raccoglie i nomi dei moduli Python locali (nella directory)."""
    local = set()
    for py_file in python_dir.glob('*.py'):
        if py_file.name != '__init__.py':
            local.add(py_file.stem)
    return local

def extract_imports(py_file: Path) -> Set[str]:
    """Estrae tutti i moduli importati da un file Python."""
    imports = set()
    try:
        with open(py_file, 'r', encoding='utf-8') as f:
            tree = ast.parse(f.read(), filename=str(py_file))
        
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.add(alias.name.split('.')[0])
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    imports.add(node.module.split('.')[0])
    except Exception as e:
        print(f"Error parsing {py_file}: {e}", file=sys.stderr)
    return imports

def generate_requirements(python_dir: Path, main_files: list[str]) -> str:
    """Genera il contenuto di requirements.txt basato sulle importazioni."""
    all_imports = set()
    
    for file in main_files:
        file_path = python_dir / file
        if file_path.exists():
            all_imports.update(extract_imports(file_path))
    
    # Escludi standard library e moduli locali
    std_libs = get_standard_lib_modules()
    local_modules = get_local_modules(python_dir)
    third_party = all_imports - std_libs - local_modules
    
    # Mappa delle versioni note (PyPI package name -> versione)
    version_map = {
        'openpyxl': 'openpyxl>=3.1.0',
        'flask': 'Flask>=2.0.0',
        'flask_cors': 'flask-cors>=3.0.0',
    }
    
    lines = []
    for pkg in sorted(third_party):
        if pkg in version_map:
            lines.append(version_map[pkg])
        else:
            lines.append(pkg)
    
    header = "# Auto-generated by generate.py - DO NOT EDIT MANUALLY\n"
    content = header + '\n'.join(lines)
    return content + '\n' if content else header

def update_requirements_file(python_dir: Path):
    """Aggiorna il file requirements.txt."""
    main_files = ['save_pandetta.py']
    requirements_txt = python_dir / 'requirements.txt'
    
    new_content = generate_requirements(python_dir, main_files)
    
    if requirements_txt.exists():
        old_content = requirements_txt.read_text(encoding='utf-8')
        if new_content == old_content:
            print("requirements.txt is already up to date.")
            return False
    
    requirements_txt.write_text(new_content, encoding='utf-8')
    print("Updated requirements.txt:")
    print(new_content)
    return True

def main():
    python_dir = Path(__file__).parent
    update_requirements_file(python_dir)

if __name__ == '__main__':
    main()
